"""Guarded interactive python-oracledb access for human-initiated surfaces."""

from apex_pilot.interactive.browse import InteractiveBrowseError, InteractiveBrowseService
from apex_pilot.interactive.pool import (
    DEFAULT_IDLE_TIMEOUT_SECONDS,
    DEFAULT_WARNING_LEAD_SECONDS,
    READONLY_POOL_MEMBER_TIMEOUT_SECONDS,
    DedicatedSessionHandle,
    DedicatedSessionLimitError,
    DisconnectReason,
    InteractiveDriverBinding,
    InteractiveOraclePool,
    InteractivePoolError,
    InteractivePoolState,
    InteractivePoolStatus,
    OraclePoolDriver,
    PoolNotOpenError,
    clamp_idle_timeout_seconds,
)
from apex_pilot.interactive.sessions import DedicatedSessionPin, InteractiveSessionService
from apex_pilot.interactive.source import (
    AttachmentState,
    CompileOutcome,
    CompileRequest,
    CompileResult,
    CompileTarget,
    DatabaseSourceService,
    DocumentKind,
    OracleUnitType,
    SourceParseError,
    SourceServiceError,
    parse_database_source,
)

__all__ = [
    "AttachmentState",
    "CompileOutcome",
    "CompileRequest",
    "CompileResult",
    "CompileTarget",
    "DEFAULT_IDLE_TIMEOUT_SECONDS",
    "DEFAULT_WARNING_LEAD_SECONDS",
    "DatabaseSourceService",
    "DedicatedSessionHandle",
    "DedicatedSessionLimitError",
    "DedicatedSessionPin",
    "DisconnectReason",
    "DocumentKind",
    "InteractiveBrowseError",
    "InteractiveBrowseService",
    "InteractiveDriverBinding",
    "InteractiveOraclePool",
    "InteractivePoolError",
    "InteractivePoolState",
    "InteractivePoolStatus",
    "InteractiveSessionService",
    "OraclePoolDriver",
    "OracleUnitType",
    "PoolNotOpenError",
    "READONLY_POOL_MEMBER_TIMEOUT_SECONDS",
    "SourceParseError",
    "SourceServiceError",
    "clamp_idle_timeout_seconds",
    "parse_database_source",
]
