"""SQLcl MCP lifecycle and integration layer."""

from apex_pilot.mcp.client import SqlclMcpSdkClient, ToolActivityMcpClient
from apex_pilot.mcp.connmgr import (
    RUN_SQLCL_TOOL,
    SqlclConnectionDetails,
    build_connmgr_show_command,
    connection_details_from_mcp_payload,
    parse_connmgr_show_output,
)
from apex_pilot.mcp.connections import (
    CONNECT_TOOL,
    DISCONNECT_TOOL,
    LIST_CONNECTIONS_TOOL,
    SqlclConnectionError,
    SqlclConnectionManager,
    SqlclMcpSession,
    SqlclMcpSessionRole,
    SqlclMcpToolClient,
    SqlclReadOnlyPool,
    SqlclReadOnlySessionError,
    SqlclSavedConnection,
    SqlRequestAccess,
    normalize_saved_connection_name,
    parse_saved_connections,
)
from apex_pilot.mcp.sqlcl import (
    SQLCL_MINIMUM_VERSION,
    SUPPORTED_JAVA_MAJOR_VERSIONS,
    CommandResult,
    SqlclMcpConfig,
    SqlclMcpError,
    SqlclMcpService,
    SqlclMcpServiceError,
    SqlclPreflightError,
    SqlclPreflightResult,
    build_sqlcl_environment,
    find_sqlcl_binary,
    parse_java_major_version,
    parse_sqlcl_version,
    resolve_java_binary,
    run_sqlcl_preflight,
)

__all__ = [
    "CONNECT_TOOL",
    "DISCONNECT_TOOL",
    "LIST_CONNECTIONS_TOOL",
    "RUN_SQLCL_TOOL",
    "SQLCL_MINIMUM_VERSION",
    "SUPPORTED_JAVA_MAJOR_VERSIONS",
    "CommandResult",
    "SqlRequestAccess",
    "SqlclConnectionDetails",
    "SqlclConnectionError",
    "SqlclConnectionManager",
    "SqlclMcpConfig",
    "SqlclMcpError",
    "SqlclMcpSdkClient",
    "SqlclMcpService",
    "SqlclMcpServiceError",
    "SqlclMcpSession",
    "SqlclMcpSessionRole",
    "SqlclMcpToolClient",
    "SqlclPreflightError",
    "SqlclPreflightResult",
    "SqlclReadOnlyPool",
    "SqlclReadOnlySessionError",
    "SqlclSavedConnection",
    "ToolActivityMcpClient",
    "build_connmgr_show_command",
    "build_sqlcl_environment",
    "connection_details_from_mcp_payload",
    "find_sqlcl_binary",
    "normalize_saved_connection_name",
    "parse_connmgr_show_output",
    "parse_java_major_version",
    "parse_saved_connections",
    "parse_sqlcl_version",
    "resolve_java_binary",
    "run_sqlcl_preflight",
]
